### ISSUE TITLE
Environment for Barret WAM robotic arm simulation in Gazebo

### ISSUE THREAD

**Issue by tunglm2203** [jangirrishabh/Overcoming-exploration-from-demos#6]
Did you public environment for Barret WAM robotic arm simulation in Gazebo in multi-block stacking task ?

**Comment by jangirrishabh** [comment]
Hello @tunglm2203 I am extremely sorry but I do not have the rights to public the Barret WAM simulation, it belongs to my workplace. I would like to advise you to check out Mujoco simulation software, the one I have used in the second part, it is really easy to use and you can get a student license for 1 year.
